services:
  - type: web
    name: scalen-cms
    runtime: node
    buildCommand: npm install
    startCommand: bash start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: /opt/render/project/src/public/uploads/data.db
    disk:
      name: uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
