services:
  - type: web
    name: scalen-cms
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    disk:
      name: uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
